from django.conf.urls import url
from main import views
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login_form, name='login'),
    url(r'^signup/$', views.signup,name='signup'),
    url(r'^loginReq/', views.login_req, name ='loginReq'),
    url(r'^gestionproductos/$', views.gestionproductos,name='gestionproductos'),
    url(r'^vendedorprofilepage/$', views.vendedorprofilepage,name='vendedorprofilepage'),
    url(r'^formView/', views.form_view, name='formView'),
    url(r'^logout/', views.log_out, name='logout'),
    url(r'^register/', views.register, name='register'),
    url(r'^loggedin/', views.loggedin, name='loggedin'),
    url(r'^productoReq/', views.producto_req, name='productoReq'),
    url(r'^vistaVendedorPorAlumno/', views.vista_vendedor_por_alumno, name='vistaVendedorPorAlumno'),
    url(r'^cambiarEstado/$', views.cambiar_estado, name='cambiarEstado'),
    url(r'^editarVendedor/$', views.editar_vendedor, name='editarVendedor'),
    url(r'^editarDatos/$', views.editar_datos, name='editarDatos'),
    url(r'^inicioAlumno/', views.inicio_alumno, name='inicioAlumno'),
    url(r'^borrarUsuario/', views.borrar_usuario, name='borrarUsuario'),
    url(r'^borrarProducto/', views.borrar_producto, name='borrarProducto'),
    url(r'^editarProducto/', views.editar_producto, name='editarProducto'),
    url(r'^cambiarFavorito/', views.cambiar_favorito, name='cambiarFavorito'),
    url(r'^vistaVendedorPorAlumnoSinLogin/', views.vista_vendedor_por_alumno_sin_login, name='vistaVendedorPorAlumnoSinLogin'),
    url(r'^editarPerfilAlumno/', views.editar_perfil_alumno, name='editarPerfilAlumno'),
    url(r'^procesarPerfilAlumno/', views.procesar_perfil_alumno, name='procesarPerfilAlumno'),
    url(r'^editarUsuario/', views.editar_usuario, name='editarUsuario'),
    url(r'^agregarAvatar/', views.agregar_avatar, name='agregarAvatar'),
    url(r'^signupAdmin/$', views.signup_admin, name='signupAdmin'),
    url(r'^registerAdmin/$', views.register_admin, name='registerAdmin'),
    url(r'^getStock/$', views.get_stock, name='getStock'),
    url(r'^verificarEmail/$', views.verificar_email, name='verificarEmail'),
    url(r'^adminEdit/$', views.admin_edit, name='adminEdit'),
    url(r'^editarUsuarioAdmin/$', views.editar_usuario_admin, name='editarUsuarioAdmin'),
    url(r'^loginAdmin/$', views.login_admin, name='loginAdmin'),
    url(r'^createTransaction/$', views.create_transaction, name='createTransaction'),
    url(r'^fijoDashboard/$', views.fijo_dashboard, name='fijoDashboard'),
    url(r'^ambulanteDashboard/$', views.ambulante_dashboard, name='ambulanteDashboard'),


]
